Make `UrlPath` a distinct type
The feels like an obvious use case for `NewType` but sadly it doesn't
work. First we get the error:

    Error constructing plugin instance of NewSemanalDjangoPlugin

    Traceback (most recent call last):
      File "/home/dave/.virtualenvs/ebm-airlock/bin/mypy", line 8, in <module>
        sys.exit(console_entry())
                 ^^^^^^^^^^^^^^^
      ...
      File "/home/dave/projects/ebmdatalab/airlock/local_db/models.py", line 11, in <module>
        from airlock.business_logic import RequestFileType, Status
      File "/home/dave/projects/ebmdatalab/airlock/airlock/business_logic.py", line 27, in <module>
        ROOT_PATH = UrlPath()  # empty path
                    ^^^^^^^^^
    TypeError: _typing._idfunc() takes exactly one argument (0 given)

Then if we fix that by providing an empty argument to `UrlPath` we get a
load of type errors:

    airlock/business_logic.py:27: error: Argument 1 to "UrlPath" has incompatible type "str"; expected "PurePosixPath"  [arg-type]
    airlock/business_logic.py:256: error: Argument 1 to "UrlPath" has incompatible type "UrlPath | str"; expected "PurePosixPath"  [arg-type]
    airlock/business_logic.py:258: error: Argument 1 to "UrlPath" has incompatible type "*tuple[str, ...]"; expected "PurePosixPath"  [arg-type]

I think this might be because `PurePosixPath` is not itself correctly
type annotated.