Remove broken static typing
Upgrading to django-stubs 6.1.0 triggered some mypy errors:
```
tests/integration/views/test_request.py:2552: error: "TemplateResponse" has no attribute "context"  [attr-defined]
tests/integration/views/test_request.py:2595: error: "TemplateResponse" has no attribute "context"  [attr-defined]
tests/integration/views/test_request.py:2619: error: "TemplateResponse" has no attribute "context"  [attr-defined]
```

This is because the response object in tests is wrapped in another type with
some extra attributes like `context`. Calling `isinstance` gives type hints to
mypy, which is unaware of the `context` attribute:
https://mypy.readthedocs.io/en/stable/type_narrowing.html#type-narrowing-expressions

We're not sure why the upgrade triggered this error, or exactly why the
`isinstance` line was needed before. It was added in 9d7b95d when we enabled
mypy: https://github.com/opensafely-core/airlock/commit/9d7b95dc5fddd2c6474b269dffff6c183d5abca3
But removing it doesn't seem to cause any issues before or after the
django-stubs upgrade.